//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/zOthers/TouchInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TouchInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchInput"",
    ""maps"": [
        {
            ""name"": ""TouchControls"",
            ""id"": ""f69246f5-42e5-43b6-a89a-ff87b90cd197"",
            ""actions"": [
                {
                    ""name"": ""PanningContact"",
                    ""type"": ""Button"",
                    ""id"": ""803f73cb-596b-4d91-a3c9-e157852918f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PanningContactPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""76d17120-c9e4-4b25-9042-c6754b136ec9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryHoldPosition"",
                    ""type"": ""Value"",
                    ""id"": ""b1d83950-ee11-428d-b02e-7a26b2b1ddb2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryHoldPosition"",
                    ""type"": ""Value"",
                    ""id"": ""293e5769-05d4-4e84-99f9-bd8627d0a25a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryHoldContact"",
                    ""type"": ""Button"",
                    ""id"": ""e1b6e439-37bf-44d9-9a49-839b69c6d467"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryHoldDelta"",
                    ""type"": ""Value"",
                    ""id"": ""6060bb04-82ce-4f09-9599-7d1d7fee2495"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryHoldDelta"",
                    ""type"": ""Value"",
                    ""id"": ""709c303e-4810-4203-a3a8-ce71a67edc69"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceBuild"",
                    ""type"": ""Button"",
                    ""id"": ""84647447-54fd-493f-af8a-710f84887801"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceBuildPosition"",
                    ""type"": ""Value"",
                    ""id"": ""a4ac3015-c226-4e99-a1dc-c8d391633914"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ed02b80b-04b8-448a-8cd9-6bed10d2f4a3"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PanningContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82c4a47c-6ca0-45d5-9a10-82ea3e2832fe"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PanningContactPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a5b777f-4336-4f3d-97f2-f2e4ddcfb0fc"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryHoldPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8785cea-e113-4fb4-849e-15d55230c5e5"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryHoldPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68c4850a-3820-41db-aee3-84cba469c26f"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryHoldContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""997c91c1-6b7c-44b5-8b8e-0e934b97eb7c"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryHoldDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4dfce0a-9c3a-47e1-b845-1506d56e37d1"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryHoldDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""713acc71-6717-4611-9025-c68bd0f45925"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceBuild"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd6fcdb7-bcfb-4ba2-ab36-d5452cc613db"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceBuildPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TouchControls
        m_TouchControls = asset.FindActionMap("TouchControls", throwIfNotFound: true);
        m_TouchControls_PanningContact = m_TouchControls.FindAction("PanningContact", throwIfNotFound: true);
        m_TouchControls_PanningContactPosition = m_TouchControls.FindAction("PanningContactPosition", throwIfNotFound: true);
        m_TouchControls_PrimaryHoldPosition = m_TouchControls.FindAction("PrimaryHoldPosition", throwIfNotFound: true);
        m_TouchControls_SecondaryHoldPosition = m_TouchControls.FindAction("SecondaryHoldPosition", throwIfNotFound: true);
        m_TouchControls_SecondaryHoldContact = m_TouchControls.FindAction("SecondaryHoldContact", throwIfNotFound: true);
        m_TouchControls_PrimaryHoldDelta = m_TouchControls.FindAction("PrimaryHoldDelta", throwIfNotFound: true);
        m_TouchControls_SecondaryHoldDelta = m_TouchControls.FindAction("SecondaryHoldDelta", throwIfNotFound: true);
        m_TouchControls_PlaceBuild = m_TouchControls.FindAction("PlaceBuild", throwIfNotFound: true);
        m_TouchControls_PlaceBuildPosition = m_TouchControls.FindAction("PlaceBuildPosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TouchControls
    private readonly InputActionMap m_TouchControls;
    private ITouchControlsActions m_TouchControlsActionsCallbackInterface;
    private readonly InputAction m_TouchControls_PanningContact;
    private readonly InputAction m_TouchControls_PanningContactPosition;
    private readonly InputAction m_TouchControls_PrimaryHoldPosition;
    private readonly InputAction m_TouchControls_SecondaryHoldPosition;
    private readonly InputAction m_TouchControls_SecondaryHoldContact;
    private readonly InputAction m_TouchControls_PrimaryHoldDelta;
    private readonly InputAction m_TouchControls_SecondaryHoldDelta;
    private readonly InputAction m_TouchControls_PlaceBuild;
    private readonly InputAction m_TouchControls_PlaceBuildPosition;
    public struct TouchControlsActions
    {
        private @TouchInput m_Wrapper;
        public TouchControlsActions(@TouchInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @PanningContact => m_Wrapper.m_TouchControls_PanningContact;
        public InputAction @PanningContactPosition => m_Wrapper.m_TouchControls_PanningContactPosition;
        public InputAction @PrimaryHoldPosition => m_Wrapper.m_TouchControls_PrimaryHoldPosition;
        public InputAction @SecondaryHoldPosition => m_Wrapper.m_TouchControls_SecondaryHoldPosition;
        public InputAction @SecondaryHoldContact => m_Wrapper.m_TouchControls_SecondaryHoldContact;
        public InputAction @PrimaryHoldDelta => m_Wrapper.m_TouchControls_PrimaryHoldDelta;
        public InputAction @SecondaryHoldDelta => m_Wrapper.m_TouchControls_SecondaryHoldDelta;
        public InputAction @PlaceBuild => m_Wrapper.m_TouchControls_PlaceBuild;
        public InputAction @PlaceBuildPosition => m_Wrapper.m_TouchControls_PlaceBuildPosition;
        public InputActionMap Get() { return m_Wrapper.m_TouchControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchControlsActions set) { return set.Get(); }
        public void SetCallbacks(ITouchControlsActions instance)
        {
            if (m_Wrapper.m_TouchControlsActionsCallbackInterface != null)
            {
                @PanningContact.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPanningContact;
                @PanningContact.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPanningContact;
                @PanningContact.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPanningContact;
                @PanningContactPosition.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPanningContactPosition;
                @PanningContactPosition.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPanningContactPosition;
                @PanningContactPosition.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPanningContactPosition;
                @PrimaryHoldPosition.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPrimaryHoldPosition;
                @PrimaryHoldPosition.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPrimaryHoldPosition;
                @PrimaryHoldPosition.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPrimaryHoldPosition;
                @SecondaryHoldPosition.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldPosition;
                @SecondaryHoldPosition.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldPosition;
                @SecondaryHoldPosition.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldPosition;
                @SecondaryHoldContact.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldContact;
                @SecondaryHoldContact.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldContact;
                @SecondaryHoldContact.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldContact;
                @PrimaryHoldDelta.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPrimaryHoldDelta;
                @PrimaryHoldDelta.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPrimaryHoldDelta;
                @PrimaryHoldDelta.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPrimaryHoldDelta;
                @SecondaryHoldDelta.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldDelta;
                @SecondaryHoldDelta.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldDelta;
                @SecondaryHoldDelta.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnSecondaryHoldDelta;
                @PlaceBuild.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPlaceBuild;
                @PlaceBuild.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPlaceBuild;
                @PlaceBuild.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPlaceBuild;
                @PlaceBuildPosition.started -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPlaceBuildPosition;
                @PlaceBuildPosition.performed -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPlaceBuildPosition;
                @PlaceBuildPosition.canceled -= m_Wrapper.m_TouchControlsActionsCallbackInterface.OnPlaceBuildPosition;
            }
            m_Wrapper.m_TouchControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PanningContact.started += instance.OnPanningContact;
                @PanningContact.performed += instance.OnPanningContact;
                @PanningContact.canceled += instance.OnPanningContact;
                @PanningContactPosition.started += instance.OnPanningContactPosition;
                @PanningContactPosition.performed += instance.OnPanningContactPosition;
                @PanningContactPosition.canceled += instance.OnPanningContactPosition;
                @PrimaryHoldPosition.started += instance.OnPrimaryHoldPosition;
                @PrimaryHoldPosition.performed += instance.OnPrimaryHoldPosition;
                @PrimaryHoldPosition.canceled += instance.OnPrimaryHoldPosition;
                @SecondaryHoldPosition.started += instance.OnSecondaryHoldPosition;
                @SecondaryHoldPosition.performed += instance.OnSecondaryHoldPosition;
                @SecondaryHoldPosition.canceled += instance.OnSecondaryHoldPosition;
                @SecondaryHoldContact.started += instance.OnSecondaryHoldContact;
                @SecondaryHoldContact.performed += instance.OnSecondaryHoldContact;
                @SecondaryHoldContact.canceled += instance.OnSecondaryHoldContact;
                @PrimaryHoldDelta.started += instance.OnPrimaryHoldDelta;
                @PrimaryHoldDelta.performed += instance.OnPrimaryHoldDelta;
                @PrimaryHoldDelta.canceled += instance.OnPrimaryHoldDelta;
                @SecondaryHoldDelta.started += instance.OnSecondaryHoldDelta;
                @SecondaryHoldDelta.performed += instance.OnSecondaryHoldDelta;
                @SecondaryHoldDelta.canceled += instance.OnSecondaryHoldDelta;
                @PlaceBuild.started += instance.OnPlaceBuild;
                @PlaceBuild.performed += instance.OnPlaceBuild;
                @PlaceBuild.canceled += instance.OnPlaceBuild;
                @PlaceBuildPosition.started += instance.OnPlaceBuildPosition;
                @PlaceBuildPosition.performed += instance.OnPlaceBuildPosition;
                @PlaceBuildPosition.canceled += instance.OnPlaceBuildPosition;
            }
        }
    }
    public TouchControlsActions @TouchControls => new TouchControlsActions(this);
    public interface ITouchControlsActions
    {
        void OnPanningContact(InputAction.CallbackContext context);
        void OnPanningContactPosition(InputAction.CallbackContext context);
        void OnPrimaryHoldPosition(InputAction.CallbackContext context);
        void OnSecondaryHoldPosition(InputAction.CallbackContext context);
        void OnSecondaryHoldContact(InputAction.CallbackContext context);
        void OnPrimaryHoldDelta(InputAction.CallbackContext context);
        void OnSecondaryHoldDelta(InputAction.CallbackContext context);
        void OnPlaceBuild(InputAction.CallbackContext context);
        void OnPlaceBuildPosition(InputAction.CallbackContext context);
    }
}
